"""Stage 6 FIX verification: packages a candidate-vs-shipped bake-off as a Kaggle kernel
attached to the competition, pushes it, and (with --wait) polls until it finishes and pulls
the result back down.

Why a kernel and not another local tools/bakeoff.py run: CLAUDE.md wants the FIX gate to be
400+ games before a candidate is trusted enough to ship, which is slow on this laptop's
hardware-constrained setup (max 2 sim workers). Attaching the kernel to the competition
(kernel-metadata.json's competition_sources) gets Kaggle's own mounted copy of the cg SDK /
card data, the same thing any competitor sees opening a notebook from the competition page --
we never upload our own copy as a dataset, which matters because that SDK/card data is
competition "Pokémon Elements" and CLAUDE.md's Data-use constraints forbid redistributing it.

KNOWN UNKNOWNS (first real use of this script is also its first real test):
  - The exact /kaggle/input/... mount path for a competition-attached kernel. The driver
    script below tries a short list of plausible paths and, if none work, prints what IS
    under /kaggle/input so a human can fix CANDIDATE_SDK_PATHS in one place.
  - Real per-game wall-clock time at Kaggle's kernel CPU allocation, and whether 400 games
    fit comfortably inside a session before hitting a runtime limit. Start with a smaller
    --games value the first time to sanity-check timing before trusting an overnight run.

Usage:
  .venv/Scripts/python scripts/build_kernel_bakeoff.py \\
      --shipped-weights runs/tune_run1/winner_weights.json \\
      --candidate-weights runs/candidate_fix/weights.json \\
      --games 400 --wait
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from kaggle_common import SIMULATION_COMPETITION, get_kaggle_username, kaggle_cmd  # noqa: E402

SRC_DIR = os.path.join(ROOT, "src")
AGENTS_DIR = os.path.join(ROOT, "agents")
DECK_PATH = os.path.join(ROOT, "decks", "crustle_wall_deck.csv")
KERNEL_ROOT = os.path.join(ROOT, "runs", "kernel_bakeoff")

MODULES_TO_COPY = ["sdk_path.py", "obs.py", "baseline.py", "determinize.py"]

DRIVER_TEMPLATE = '''"""Kernel-side driver for a shipped-vs-candidate SearchScorer bake-off. Auto-generated by
scripts/build_kernel_bakeoff.py -- edit that script, not this file, if the approach changes.
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# --- locate the competition-mounted cg SDK -------------------------------------------------
CANDIDATE_SDK_PATHS = [
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle",
]
for p in CANDIDATE_SDK_PATHS:
    if os.path.isdir(p) and os.path.exists(os.path.join(p, "cg")):
        os.environ["CG_SDK_PATH"] = p  # sdk_path.py inserts this dir, then does `import cg`
        break
else:
    print("WARNING: none of CANDIDATE_SDK_PATHS had a cg/ dir. Contents of /kaggle/input:")
    for root, dirs, files in os.walk("/kaggle/input"):
        print(" ", root, dirs, files[:10])
        if root.count(os.sep) > 3:
            dirs[:] = []

from sdk_path import ensure_cg_importable  # noqa: E402
ensure_cg_importable()
from cg.game import battle_start, battle_select, battle_finish  # noqa: E402
from search_scorer import make_agent, load_weights  # noqa: E402

GAMES = {games}
SEED_BASE = {seed_base}
SHIPPED_WEIGHTS = load_weights("shipped_weights.json") if os.path.exists("shipped_weights.json") else None
CANDIDATE_WEIGHTS = load_weights("candidate_weights.json") if os.path.exists("candidate_weights.json") else None

with open("deck.csv") as f:
    DECK = [int(x) for x in f.read().split("\\n")[:60]]


def play_one(seed: int, candidate_seat: int) -> str:
    random.seed(seed)
    candidate_agent = make_agent(DECK, weights=CANDIDATE_WEIGHTS)
    shipped_agent = make_agent(DECK, weights=SHIPPED_WEIGHTS)
    agents = {{candidate_seat: candidate_agent, 1 - candidate_seat: shipped_agent}}
    obs, start_data = battle_start(DECK, DECK)
    if obs is None:
        return "crash"
    for _ in range(6000):
        st = obs.get("current")
        if st and st.get("result", -1) != -1:
            battle_finish()
            r = st["result"]
            if r == 2:
                return "draw"
            return "candidate_win" if r == candidate_seat else "candidate_loss"
        yi = st["yourIndex"]
        try:
            index_list = agents[yi](obs)
        except Exception:
            return "candidate_loss" if yi == candidate_seat else "candidate_win"
        obs = battle_select(index_list)
    return "crash"


def main() -> None:
    wins = losses = draws = crashes = 0
    for i in range(GAMES):
        seed = SEED_BASE + i
        candidate_seat = i % 2
        outcome = play_one(seed, candidate_seat)
        if outcome == "candidate_win":
            wins += 1
        elif outcome == "candidate_loss":
            losses += 1
        elif outcome == "draw":
            draws += 1
        else:
            crashes += 1
        if (i + 1) % 20 == 0:
            print(f"progress: {{i + 1}}/{{GAMES}} (wins={{wins}} losses={{losses}} "
                  f"draws={{draws}} crashes={{crashes}})", flush=True)

    n_decided = wins + losses + draws
    win_rate = (wins + 0.5 * draws) / n_decided if n_decided else 0.0
    # normal approx 95% CI, consistent with how prior local bake-offs were read
    import math
    se = math.sqrt(win_rate * (1 - win_rate) / n_decided) if n_decided else 0.0
    ci = (max(0.0, win_rate - 1.96 * se), min(1.0, win_rate + 1.96 * se))

    result = {{
        "games": GAMES, "wins": wins, "losses": losses, "draws": draws, "crashes": crashes,
        "candidate_win_rate": win_rate, "win_rate_95ci": ci,
    }}
    print("RESULT " + json.dumps(result))
    with open("bakeoff_result.json", "w") as f:
        json.dump(result, f, indent=2)


if __name__ == "__main__":
    main()
'''

KERNEL_METADATA_TEMPLATE = {
    "id": "",  # filled in per kernel slug
    "title": "",
    "code_file": "driver.py",
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": False,
    "enable_internet": False,
    "competition_sources": [SIMULATION_COMPETITION],
    "dataset_sources": [],
    "kernel_sources": [],
}


def build(candidate_weights: str | None, shipped_weights: str | None, games: int,
          seed_base: int, slug: str) -> str:
    kernel_dir = os.path.join(KERNEL_ROOT, slug)
    if os.path.isdir(kernel_dir):
        shutil.rmtree(kernel_dir)
    os.makedirs(kernel_dir)

    for module in MODULES_TO_COPY:
        shutil.copy2(os.path.join(SRC_DIR, module), os.path.join(kernel_dir, module))
    shutil.copy2(os.path.join(AGENTS_DIR, "search_scorer.py"),
                 os.path.join(kernel_dir, "search_scorer.py"))
    shutil.copy2(DECK_PATH, os.path.join(kernel_dir, "deck.csv"))
    if candidate_weights:
        shutil.copy2(candidate_weights, os.path.join(kernel_dir, "candidate_weights.json"))
    if shipped_weights:
        shutil.copy2(shipped_weights, os.path.join(kernel_dir, "shipped_weights.json"))

    with open(os.path.join(kernel_dir, "driver.py"), "w", encoding="utf-8") as f:
        f.write(DRIVER_TEMPLATE.format(games=games, seed_base=seed_base))

    metadata = dict(KERNEL_METADATA_TEMPLATE)
    metadata["id"] = f"{get_kaggle_username()}/{slug}"
    metadata["title"] = slug.replace("-", " ")
    with open(os.path.join(kernel_dir, "kernel-metadata.json"), "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"Kernel package assembled at {kernel_dir} (id={metadata['id']})")
    return kernel_dir


def push(kernel_dir: str) -> None:
    cmd = kaggle_cmd("kernels", "push", "-p", kernel_dir)
    subprocess.run(cmd, check=True)


def poll_and_fetch(slug: str, kernel_dir: str, poll_interval_s: float = 30.0,
                    timeout_s: float = 3600.0) -> dict | None:
    kernel_ref = f"{get_kaggle_username()}/{slug}"
    status_cmd = kaggle_cmd("kernels", "status", kernel_ref)
    start = time.time()
    while time.time() - start < timeout_s:
        result = subprocess.run(status_cmd, capture_output=True, text=True)
        print(result.stdout.strip())
        if "complete" in result.stdout.lower():
            break
        if "error" in result.stdout.lower() or "failed" in result.stdout.lower():
            print("Kernel run failed -- fetch output anyway for the error log.",
                  file=sys.stderr)
            break
        time.sleep(poll_interval_s)
    else:
        print(f"Timed out after {timeout_s}s waiting for kernel completion.", file=sys.stderr)
        return None

    output_cmd = kaggle_cmd("kernels", "output", kernel_ref, "-p", kernel_dir)
    subprocess.run(output_cmd, check=True)
    result_path = os.path.join(kernel_dir, "bakeoff_result.json")
    if os.path.exists(result_path):
        with open(result_path, encoding="utf-8") as f:
            return json.load(f)
    print(f"No bakeoff_result.json found in kernel output at {kernel_dir} -- check the "
          f"kernel's log output for errors (most likely the CG_SDK_PATH mount-path unknown "
          f"flagged in this script's docstring).", file=sys.stderr)
    return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate-weights", required=True)
    ap.add_argument("--shipped-weights", default=None,
                     help="omit to bake off against agents/search_scorer.py's module default")
    ap.add_argument("--games", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--slug", default=None,
                     help="kernel slug; defaults to search-scorer-bakeoff-<date>")
    ap.add_argument("--push", action="store_true", help="actually push to Kaggle")
    ap.add_argument("--wait", action="store_true",
                     help="poll until the kernel finishes and download bakeoff_result.json")
    args = ap.parse_args()

    slug = args.slug or f"search-scorer-bakeoff-{datetime.date.today().isoformat()}"
    kernel_dir = build(args.candidate_weights, args.shipped_weights, args.games, args.seed,
                        slug)

    if not args.push:
        print("Package built but not pushed (pass --push). Review kernel-metadata.json's "
              "\"id\" field first.")
        return

    push(kernel_dir)
    if args.wait:
        result = poll_and_fetch(slug, kernel_dir)
        if result:
            print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
