"""Stage 6 v2 gate: packages a search_scorer CODE SNAPSHOT (a file path, not a weights overlay
-- for a tie-break/logic change, not a weight change) vs. the local rule-based `baseline` agent
as a Kaggle kernel, runs it at 4-worker parallelism, and (with --wait) polls until it finishes
and pulls the result back down. See docs/tie_break_v2_2026-07-23.md for why.

Run this TWICE with the same --seed, once per code snapshot (v1 frozen, v2 working tree), to
get a paired-by-seed win rate comparison against the common `baseline` opponent -- that's
"winrate v1 vs v2" read correctly (see the plan/report: there is no direct v1-vs-v2 match).

PACKAGING (confirmed 2026-07-23, the hard way): `kaggle kernels push -p <dir>` for a
kernel_type "script" does NOT upload sibling files alongside the entry `code_file` -- a real
kernel run's downloaded log showed `/kaggle/src` containing only `['__script__.ipynb',
'script.py']`, i.e. every other file in the pushed directory (sdk_path.py, obs.py, baseline.py,
determinize.py, search_scorer.py, deck.csv) was silently dropped. `scripts/build_kernel_
bakeoff.py` has this exact same latent bug (copies sibling files the same way) -- it was never
actually exercised end-to-end before this discovery. The fix here: package everything as ONE
self-contained driver.py. Each required module's source is read from disk, base64-encoded (so
no quoting/escaping of the source's own quotes/braces/backslashes is ever needed), embedded as
a literal, and installed into sys.modules via exec() at driver startup, in dependency order,
before any `from sdk_path import ...`-style cross-import happens. deck.csv's 60 card ids are
embedded as a literal Python list for the same reason.

CHECKPOINTING (best-effort, confirmed via AskUserQuestion): Kaggle kernels are stateless
between separate `kernel push` runs, so true mid-run resume isn't literally possible. Instead:
(1) the driver writes its result file every ~20 games, not just at the end, so a timed-out/
killed kernel still leaves usable partial data in kernel output; (2) if `--wait` detects the
fetched result is partial (games_completed < the games requested this run) or the kernel
errored, this script automatically builds and pushes a FOLLOW-UP kernel for just the remaining
games (continuing the same seed sequence) and merges the two partial results locally into one
combined JSON -- so a single `--push --wait` invocation transparently recovers from one
interruption without discarding completed games.

Output-directory and SDK-mount-path handling (also confirmed the hard way on real kernel runs):
`/kaggle/working` is where `kaggle kernels output` looks, NOT `/kaggle/src` (where the script
itself runs from) -- output files are written there explicitly. The competition-attached SDK
mount is at `/kaggle/input/competitions/pokemon-tcg-ai-battle/...` (an extra "competitions/"
segment the very first guess omitted).

Usage:
  .venv/Scripts/python scripts/build_kernel_vs_baseline.py \\
      --code runs/v2_tie_break/search_scorer_v1_snapshot.py --label v1 \\
      --games 400 --seed 0 --workers 4 --slug tie-break-v1-vs-baseline-2026-07-23 \\
      --push --wait
"""

from __future__ import annotations

import argparse
import base64
import json
import math
import os
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from kaggle_common import SIMULATION_COMPETITION, get_kaggle_username, kaggle_cmd  # noqa: E402

SRC_DIR = os.path.join(ROOT, "src")
DECK_PATH = os.path.join(ROOT, "decks", "crustle_wall_deck.csv")
KERNEL_ROOT = os.path.join(ROOT, "runs", "kernel_vs_baseline")

# Dependency order matters: obs.py imports sdk_path; baseline.py/determinize.py import obs;
# search_scorer.py imports all of the above. Installed into sys.modules in this order.
MODULE_ORDER = ["sdk_path", "obs", "baseline", "determinize", "search_scorer"]

DRIVER_TEMPLATE = r'''"""Kernel-side driver for a search_scorer-vs-baseline verification run.
Auto-generated by scripts/build_kernel_vs_baseline.py -- edit that script, not this file.
Self-contained: every project module is embedded (base64) and installed into sys.modules at
startup, since Kaggle script-kernel pushes don't carry sibling files (confirmed 2026-07-23).
"""
import base64
import json
import math
import os
import random
import sys
import types
import multiprocessing as mp

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _d in (SCRIPT_DIR, "/kaggle/working", os.getcwd()):
    if _d not in sys.path:
        sys.path.insert(0, _d)

CANDIDATE_SDK_PATHS = [
    "/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission",
    "/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission",
    "/kaggle/input/competitions/pokemon-tcg-ai-battle",
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle",
]
for p in CANDIDATE_SDK_PATHS:
    if os.path.isdir(p) and os.path.exists(os.path.join(p, "cg")):
        os.environ["CG_SDK_PATH"] = p
        break
else:
    print("WARNING: none of CANDIDATE_SDK_PATHS had a cg/ dir. Contents of /kaggle/input:")
    for root, dirs, files in os.walk("/kaggle/input"):
        print(" ", root, dirs, files[:10])
        if root.count(os.sep) > 3:
            dirs[:] = []

MODULE_SOURCES_B64 = %(module_sources_b64)r  # {name: base64-encoded source text}
MODULE_ORDER = %(module_order)r


def _install_modules():
    for name in MODULE_ORDER:
        source = base64.b64decode(MODULE_SOURCES_B64[name]).decode("utf-8")
        mod = types.ModuleType(name)
        mod.__file__ = "<embedded:%%s>" %% name
        sys.modules[name] = mod
        exec(compile(source, "<embedded:%%s>" %% name, "exec"), mod.__dict__)


_install_modules()

GAMES = %(games)d
START_GAME_INDEX = %(start_game_index)d  # global seed offset: this run covers seeds
                                          # SEED_BASE+START_GAME_INDEX .. +START_GAME_INDEX+GAMES-1
SEED_BASE = %(seed_base)d
WORKERS = %(workers)d
CHECKPOINT_EVERY = 20
DECK = %(deck)r

OUTPUT_DIR = "/kaggle/working" if os.path.isdir("/kaggle/working") else SCRIPT_DIR
RESULT_PATH = os.path.join(OUTPUT_DIR, "vs_baseline_result.json")
TRACE_PATH = os.path.join(OUTPUT_DIR, "vs_baseline_trace.jsonl")
# TRACE_PATH: one line per game, search_scorer's own decision trace -- for the mechanism/
# regression analysis (attack-decline, starvation, tied-and-lost); reuses the SAME shape
# tools/loss_review.py already knows how to read.


def play_one(task):
    seed, candidate_seat = task
    # Each worker process re-runs this module's top level (spawn) or inherits it via fork --
    # either way MODULE_SOURCES_B64 was already installed into sys.modules before Pool() was
    # created, so these imports resolve without touching the filesystem.
    from sdk_path import ensure_cg_importable
    ensure_cg_importable()
    from cg.game import battle_start, battle_select, battle_finish
    from search_scorer import make_agent
    from baseline import agent as baseline_agent_fn

    random.seed(seed)
    decisions = []
    candidate_agent = make_agent(DECK, trace_fn=decisions.append)
    agents = {candidate_seat: candidate_agent, 1 - candidate_seat: baseline_agent_fn}
    obs, start_data = battle_start(DECK, DECK)
    if obs is None:
        return {"outcome": "crash", "decisions": []}
    for _ in range(6000):
        st = obs.get("current")
        if st and st.get("result", -1) != -1:
            battle_finish()
            r = st["result"]
            outcome = "draw" if r == 2 else ("candidate_win" if r == candidate_seat
                                              else "opponent_win")
            return {"outcome": outcome, "decisions": decisions}
        yi = st["yourIndex"]
        try:
            index_list = agents[yi](obs)
        except Exception:
            outcome = "opponent_win" if yi == candidate_seat else "candidate_win"
            return {"outcome": outcome, "decisions": decisions}
        obs = battle_select(index_list)
    return {"outcome": "crash", "decisions": decisions}


def write_result(outcomes, partial):
    wins = sum(1 for o in outcomes if o == "candidate_win")
    losses = sum(1 for o in outcomes if o == "opponent_win")
    draws = sum(1 for o in outcomes if o == "draw")
    crashes = sum(1 for o in outcomes if o == "crash")
    n_decided = wins + losses + draws
    win_rate = (wins + 0.5 * draws) / n_decided if n_decided else 0.0
    se = math.sqrt(win_rate * (1 - win_rate) / n_decided) if n_decided else 0.0
    ci = (max(0.0, win_rate - 1.96 * se), min(1.0, win_rate + 1.96 * se))
    result = {
        "games_requested": GAMES, "games_completed": len(outcomes), "partial": partial,
        "start_game_index": START_GAME_INDEX, "seed_base": SEED_BASE,
        "wins": wins, "losses": losses, "draws": draws, "crashes": crashes,
        "candidate_win_rate": win_rate, "win_rate_95ci": ci,
    }
    with open(RESULT_PATH, "w") as f:
        json.dump(result, f, indent=2)
    print(("PARTIAL " if partial else "RESULT ") + json.dumps(result), flush=True)


def main():
    tasks = [(SEED_BASE + START_GAME_INDEX + i, i %% 2) for i in range(GAMES)]
    outcomes = []
    with open(TRACE_PATH, "w") as trace_f, mp.Pool(processes=WORKERS) as pool:
        for i, result in enumerate(pool.imap(play_one, tasks)):
            outcomes.append(result["outcome"])
            trace_f.write(json.dumps({"game": i, "outcome": result["outcome"],
                                       "decisions": result["decisions"]}) + "\n")
            trace_f.flush()
            if (i + 1) %% CHECKPOINT_EVERY == 0:
                write_result(outcomes, partial=True)
    write_result(outcomes, partial=False)


if __name__ == "__main__":
    main()
'''

KERNEL_METADATA_TEMPLATE = {
    "id": "",
    "title": "",
    "code_file": "driver.py",
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": False,
    "enable_internet": False,
    "competition_sources": [SIMULATION_COMPETITION],
    "dataset_sources": [],
    "kernel_sources": [],
}


def _read_module_source(name: str, search_scorer_path: str) -> str:
    if name == "search_scorer":
        path = search_scorer_path
    else:
        path = os.path.join(SRC_DIR, f"{name}.py")
    with open(path, encoding="utf-8") as f:
        return f.read()


def _read_deck(path: str) -> list[int]:
    with open(path, encoding="utf-8") as f:
        return [int(x) for x in f.read().split("\n")[:60] if x.strip()]


def build(code_path: str, games: int, start_game_index: int, seed_base: int, workers: int,
          slug: str) -> str:
    kernel_dir = os.path.join(KERNEL_ROOT, slug)
    if os.path.isdir(kernel_dir):
        # Windows occasionally holds a transient handle on a just-used directory (antivirus/
        # indexer scan, or a shell whose cwd briefly pointed inside it) -- confirmed 2026-07-23
        # this is transient, not a real conflict, so retry briefly instead of failing outright.
        for attempt in range(5):
            try:
                shutil.rmtree(kernel_dir)
                break
            except PermissionError:
                if attempt == 4:
                    raise
                time.sleep(2)
    os.makedirs(kernel_dir)

    module_sources_b64 = {
        name: base64.b64encode(_read_module_source(name, code_path).encode("utf-8")).decode(
            "ascii")
        for name in MODULE_ORDER
    }
    deck = _read_deck(DECK_PATH)

    driver_source = DRIVER_TEMPLATE % {
        "module_sources_b64": module_sources_b64,
        "module_order": MODULE_ORDER,
        "games": games,
        "start_game_index": start_game_index,
        "seed_base": seed_base,
        "workers": workers,
        "deck": deck,
    }
    with open(os.path.join(kernel_dir, "driver.py"), "w", encoding="utf-8") as f:
        f.write(driver_source)

    metadata = dict(KERNEL_METADATA_TEMPLATE)
    metadata["id"] = f"{get_kaggle_username()}/{slug}"
    metadata["title"] = slug.replace("-", " ")
    with open(os.path.join(kernel_dir, "kernel-metadata.json"), "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"Kernel package assembled at {kernel_dir} (id={metadata['id']}, "
          f"driver.py={len(driver_source)} bytes)")
    return kernel_dir


def push(kernel_dir: str) -> None:
    subprocess.run(kaggle_cmd("kernels", "push", "-p", kernel_dir), check=True)


def poll_and_fetch(slug: str, kernel_dir: str, poll_interval_s: float = 30.0,
                    timeout_s: float = 3600.0) -> dict | None:
    kernel_ref = f"{get_kaggle_username()}/{slug}"
    status_cmd = kaggle_cmd("kernels", "status", kernel_ref)
    start = time.time()
    while time.time() - start < timeout_s:
        result = subprocess.run(status_cmd, capture_output=True, text=True)
        print(result.stdout.strip())
        if "complete" in result.stdout.lower():
            break
        if "error" in result.stdout.lower() or "failed" in result.stdout.lower():
            print("Kernel run failed -- fetch output anyway for the error log/partial result.",
                  file=sys.stderr)
            break
        time.sleep(poll_interval_s)
    else:
        print(f"Timed out after {timeout_s}s waiting for kernel completion -- fetching "
              f"whatever partial output exists.", file=sys.stderr)

    output_cmd = kaggle_cmd("kernels", "output", kernel_ref, "-p", kernel_dir)
    subprocess.run(output_cmd, check=False)
    result_path = os.path.join(kernel_dir, "vs_baseline_result.json")
    if os.path.exists(result_path):
        with open(result_path, encoding="utf-8") as f:
            return json.load(f)
    print(f"No vs_baseline_result.json found in kernel output at {kernel_dir} -- check the "
          f"kernel's log.", file=sys.stderr)
    return None


def merge_results(parts: list[dict]) -> dict:
    """Combines one or more (possibly partial) run results -- from the checkpointed-resume
    follow-up kernel(s) -- into one final aggregate, recomputing win_rate/CI over the pooled
    games rather than averaging per-run rates."""
    wins = sum(p["wins"] for p in parts)
    losses = sum(p["losses"] for p in parts)
    draws = sum(p["draws"] for p in parts)
    crashes = sum(p["crashes"] for p in parts)
    n_decided = wins + losses + draws
    win_rate = (wins + 0.5 * draws) / n_decided if n_decided else 0.0
    se = math.sqrt(win_rate * (1 - win_rate) / n_decided) if n_decided else 0.0
    ci = (max(0.0, win_rate - 1.96 * se), min(1.0, win_rate + 1.96 * se))
    return {
        "games_requested": sum(p["games_requested"] for p in parts if not p.get("partial")
                                or p is parts[-1]),
        "games_completed": sum(p["games_completed"] for p in parts),
        "partial": False, "wins": wins, "losses": losses, "draws": draws, "crashes": crashes,
        "candidate_win_rate": win_rate, "win_rate_95ci": ci, "n_runs_merged": len(parts),
    }


def run_with_resume(code_path: str, label: str, games: int, seed_base: int, workers: int,
                     base_slug: str, wait_timeout_s: float) -> dict | None:
    """Pushes one kernel for `games` games; if the fetched result is partial (or missing),
    builds+pushes a follow-up kernel for the remainder, continuing the same seed sequence, and
    merges results. Bounded to a few follow-up attempts so a persistently-broken kernel doesn't
    loop forever."""
    parts = []
    start_index = 0
    remaining = games
    attempt = 0
    max_attempts = 4
    while remaining > 0 and attempt < max_attempts:
        attempt += 1
        slug = base_slug if attempt == 1 else f"{base_slug}-resume{attempt}"
        kernel_dir = build(code_path, remaining, start_index, seed_base, workers, slug)
        push(kernel_dir)
        result = poll_and_fetch(slug, kernel_dir, timeout_s=wait_timeout_s)
        if result is None:
            print(f"[{label}] attempt {attempt}: no result at all -- stopping resume attempts.",
                  file=sys.stderr)
            break
        parts.append(result)
        completed = result["games_completed"]
        start_index += completed
        remaining -= completed
        if not result.get("partial") and completed >= result["games_requested"]:
            break
        if completed == 0:
            print(f"[{label}] attempt {attempt}: 0 games completed -- stopping resume attempts "
                  f"to avoid a retry loop against a broken kernel.", file=sys.stderr)
            break
        print(f"[{label}] attempt {attempt}: {completed} games completed, {remaining} "
              f"remaining -- launching a follow-up kernel." if remaining > 0 else
              f"[{label}] attempt {attempt}: all {games} games completed.")

    if not parts:
        return None
    return merge_results(parts) if len(parts) > 1 else parts[0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--code", required=True,
                     help="path to the search_scorer.py CODE SNAPSHOT to package (e.g. the "
                          "frozen v1 copy, or the current working-tree v2 file)")
    ap.add_argument("--label", required=True, help="e.g. v1 or v2 -- used in the slug/output")
    ap.add_argument("--games", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0, help="shared SEED_BASE -- use the SAME "
                     "value for both the v1 and v2 runs so they're paired by seed")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--slug", default=None)
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--wait", action="store_true")
    ap.add_argument("--wait-timeout-s", type=float, default=3600.0)
    ap.add_argument("--out", default=None, help="where to write the final merged result JSON "
                     "locally (default: runs/kernel_vs_baseline/<slug>_final_result.json)")
    args = ap.parse_args()

    slug = args.slug or f"tie-break-{args.label}-vs-baseline-2026-07-23"
    out_path = args.out or os.path.join(KERNEL_ROOT, f"{slug}_final_result.json")

    if not args.push:
        build(args.code, args.games, 0, args.seed, args.workers, slug)
        print("Package built but not pushed (pass --push). Review kernel-metadata.json's "
              "\"id\" field first.")
        return

    if not args.wait:
        kernel_dir = build(args.code, args.games, 0, args.seed, args.workers, slug)
        push(kernel_dir)
        print("Pushed without --wait -- check status manually with "
              f"`kaggle kernels status {get_kaggle_username()}/{slug}`.")
        return

    result = run_with_resume(args.code, args.label, args.games, args.seed, args.workers, slug,
                              args.wait_timeout_s)
    if result is None:
        sys.exit(f"[{args.label}] no usable result after all resume attempts.")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"\n[{args.label}] FINAL: {json.dumps(result, indent=2)}")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
