"""Stage 6 v3 gate, leg (a): packages TWO search_scorer CODE SNAPSHOTS (e.g. the frozen v1 --
pre-tie-break, actually-shipped-to-Kaggle -- and the post-A1 v3 working tree) as a single
Kaggle kernel and plays them directly against each other, 4-worker parallelism, --wait polls
and pulls the result back down. Fork of scripts/build_kernel_vs_baseline.py (same proven
self-contained-driver packaging -- see that script's docstring for why sibling-file packaging
doesn't work on Kaggle script kernels, and the /kaggle/working vs /kaggle/src / SDK mount-path
details, all reused verbatim here).

The only structural difference from build_kernel_vs_baseline.py: TWO search_scorer sources are
embedded, each installed into sys.modules under a DISTINCT aliased name ("search_scorer_a" /
"search_scorer_b") instead of one "search_scorer" vs the separately-embedded baseline module.
Internal `from determinize import ...`-style imports inside each snapshot's source still resolve
correctly regardless of the outer module's own registered name, since Python's import system
checks sys.modules by the IMPORTED name, not the importing module's identity -- the shared
modules (sdk_path/obs/baseline/determinize) are installed once, before either snapshot.

Usage:
  .venv/Scripts/python scripts/build_kernel_head_to_head.py \\
      --code-a runs/v2_tie_break/search_scorer_v1_snapshot.py --label-a v1 \\
      --code-b runs/v3_voting/search_scorer_v3_snapshot.py --label-b v3 \\
      --games 400 --seed 0 --workers 4 --slug v3-v1-head-to-head-2026-07-24 \\
      --push --wait
"""

from __future__ import annotations

import argparse
import base64
import json
import math
import os
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from kaggle_common import SIMULATION_COMPETITION, get_kaggle_username, kaggle_cmd  # noqa: E402

SRC_DIR = os.path.join(ROOT, "src")
DECK_PATH = os.path.join(ROOT, "decks", "crustle_wall_deck.csv")
KERNEL_ROOT = os.path.join(ROOT, "runs", "kernel_head_to_head")

# Shared modules, installed once (identical for both snapshots -- neither v1 nor v3 changes
# sdk_path/obs/baseline/determinize). search_scorer itself is installed twice, aliased.
SHARED_MODULE_ORDER = ["sdk_path", "obs", "baseline", "determinize"]

DRIVER_TEMPLATE = r'''"""Kernel-side driver for a search_scorer-vs-search_scorer head-to-head gate.
Auto-generated by scripts/build_kernel_head_to_head.py -- edit that script, not this file.
Self-contained: every project module is embedded (base64) and installed into sys.modules at
startup (Kaggle script-kernel pushes don't carry sibling files -- confirmed 2026-07-23, see
scripts/build_kernel_vs_baseline.py). Two search_scorer snapshots are installed under distinct
aliased module names so both coexist in one process.
"""
import base64
import json
import math
import os
import random
import sys
import types
import multiprocessing as mp

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _d in (SCRIPT_DIR, "/kaggle/working", os.getcwd()):
    if _d not in sys.path:
        sys.path.insert(0, _d)

CANDIDATE_SDK_PATHS = [
    "/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission",
    "/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission",
    "/kaggle/input/competitions/pokemon-tcg-ai-battle",
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle/sample_submission",
    "/kaggle/input/pokemon-tcg-ai-battle",
]
for p in CANDIDATE_SDK_PATHS:
    if os.path.isdir(p) and os.path.exists(os.path.join(p, "cg")):
        os.environ["CG_SDK_PATH"] = p
        break
else:
    print("WARNING: none of CANDIDATE_SDK_PATHS had a cg/ dir. Contents of /kaggle/input:")
    for root, dirs, files in os.walk("/kaggle/input"):
        print(" ", root, dirs, files[:10])
        if root.count(os.sep) > 3:
            dirs[:] = []

SHARED_MODULE_SOURCES_B64 = %(shared_module_sources_b64)r  # {name: base64 source}
SHARED_MODULE_ORDER = %(shared_module_order)r
SEARCH_SCORER_A_B64 = %(search_scorer_a_b64)r
SEARCH_SCORER_B_B64 = %(search_scorer_b_b64)r
LABEL_A = %(label_a)r
LABEL_B = %(label_b)r


def _install(name, source_b64):
    source = base64.b64decode(source_b64).decode("utf-8")
    mod = types.ModuleType(name)
    mod.__file__ = "<embedded:%%s>" %% name
    sys.modules[name] = mod
    exec(compile(source, "<embedded:%%s>" %% name, "exec"), mod.__dict__)
    return mod


def _install_modules():
    for name in SHARED_MODULE_ORDER:
        _install(name, SHARED_MODULE_SOURCES_B64[name])
    _install("search_scorer_a", SEARCH_SCORER_A_B64)
    _install("search_scorer_b", SEARCH_SCORER_B_B64)


_install_modules()

GAMES = %(games)d
START_GAME_INDEX = %(start_game_index)d  # this run covers seeds
                                          # SEED_BASE+START_GAME_INDEX .. +START_GAME_INDEX+GAMES-1
SEED_BASE = %(seed_base)d
WORKERS = %(workers)d
CHECKPOINT_EVERY = 20
DECK = %(deck)r

OUTPUT_DIR = "/kaggle/working" if os.path.isdir("/kaggle/working") else SCRIPT_DIR
RESULT_PATH = os.path.join(OUTPUT_DIR, "head_to_head_result.json")
TRACE_PATH = os.path.join(OUTPUT_DIR, "head_to_head_trace.jsonl")
# TRACE_PATH: one line per game with BOTH sides' decision traces (search_scorer's own trace_fn
# shape -- same as tools/loss_review.py already knows how to read) for extra mechanism signal,
# though the v3 report's primary mechanism numbers come from the separate local vs-baseline legs.


def play_one(task):
    seed, b_seat = task  # b_seat: which seat LABEL_B (the newer snapshot) plays this game
    from sdk_path import ensure_cg_importable
    ensure_cg_importable()
    from cg.game import battle_start, battle_select, battle_finish
    import search_scorer_a
    import search_scorer_b

    random.seed(seed)
    decisions_a, decisions_b = [], []
    agent_a = search_scorer_a.make_agent(DECK, trace_fn=decisions_a.append)
    agent_b = search_scorer_b.make_agent(DECK, trace_fn=decisions_b.append)
    a_seat = 1 - b_seat
    agents = {a_seat: agent_a, b_seat: agent_b}
    obs, start_data = battle_start(DECK, DECK)
    if obs is None:
        return {"outcome": "crash", "decisions_a": [], "decisions_b": []}
    for _ in range(6000):
        st = obs.get("current")
        if st and st.get("result", -1) != -1:
            battle_finish()
            r = st["result"]
            if r == 2:
                outcome = "draw"
            elif r == b_seat:
                outcome = "b_win"
            else:
                outcome = "a_win"
            return {"outcome": outcome, "decisions_a": decisions_a, "decisions_b": decisions_b}
        yi = st["yourIndex"]
        try:
            index_list = agents[yi](obs)
        except Exception:
            outcome = "a_win" if yi == b_seat else "b_win"
            return {"outcome": outcome, "decisions_a": decisions_a, "decisions_b": decisions_b}
        obs = battle_select(index_list)
    return {"outcome": "crash", "decisions_a": decisions_a, "decisions_b": decisions_b}


def write_result(outcomes, partial):
    b_wins = sum(1 for o in outcomes if o == "b_win")
    a_wins = sum(1 for o in outcomes if o == "a_win")
    draws = sum(1 for o in outcomes if o == "draw")
    crashes = sum(1 for o in outcomes if o == "crash")
    n_decided = a_wins + b_wins + draws
    b_win_rate = (b_wins + 0.5 * draws) / n_decided if n_decided else 0.0
    se = math.sqrt(b_win_rate * (1 - b_win_rate) / n_decided) if n_decided else 0.0
    ci = (max(0.0, b_win_rate - 1.96 * se), min(1.0, b_win_rate + 1.96 * se))
    result = {
        "label_a": LABEL_A, "label_b": LABEL_B,
        "games_requested": GAMES, "games_completed": len(outcomes), "partial": partial,
        "start_game_index": START_GAME_INDEX, "seed_base": SEED_BASE,
        "a_wins": a_wins, "b_wins": b_wins, "draws": draws, "crashes": crashes,
        "b_win_rate": b_win_rate, "b_win_rate_95ci": ci,
    }
    with open(RESULT_PATH, "w") as f:
        json.dump(result, f, indent=2)
    print(("PARTIAL " if partial else "RESULT ") + json.dumps(result), flush=True)


def main():
    tasks = [(SEED_BASE + START_GAME_INDEX + i, i %% 2) for i in range(GAMES)]
    outcomes = []
    # Force 'spawn' regardless of platform default. On Linux (the real Kaggle kernel
    # container), multiprocessing defaults to 'fork' -- forking AFTER this driver has already
    # initialized the compiled cg engine bindings TWICE at module level (once per installed
    # search_scorer snapshot, each doing its own `all_card_data()`/`all_attack()` at import
    # time) is suspected to leave forked workers hanging on their first engine call. This
    # exact double-install pattern tested fine locally on Windows, which only ever has
    # 'spawn' -- consistent with a fork-specific issue rather than a logic bug. 'spawn' gives
    # every worker a fresh interpreter (re-running module install from scratch), matching what
    # already works reliably, at some worker-startup cost.
    ctx = mp.get_context("spawn")
    with open(TRACE_PATH, "w") as trace_f, ctx.Pool(processes=WORKERS) as pool:
        for i, result in enumerate(pool.imap(play_one, tasks)):
            outcomes.append(result["outcome"])
            trace_f.write(json.dumps({
                "game": i, "outcome": result["outcome"],
                "decisions_a": result["decisions_a"], "decisions_b": result["decisions_b"],
            }) + "\n")
            trace_f.flush()
            if (i + 1) %% CHECKPOINT_EVERY == 0:
                write_result(outcomes, partial=True)
    write_result(outcomes, partial=False)


if __name__ == "__main__":
    main()
'''

KERNEL_METADATA_TEMPLATE = {
    "id": "",
    "title": "",
    "code_file": "driver.py",
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": False,
    "enable_internet": False,
    "competition_sources": [SIMULATION_COMPETITION],
    "dataset_sources": [],
    "kernel_sources": [],
}


def _read_source(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


def _read_deck(path: str) -> list[int]:
    with open(path, encoding="utf-8") as f:
        return [int(x) for x in f.read().split("\n")[:60] if x.strip()]


def build(code_a: str, label_a: str, code_b: str, label_b: str, games: int,
          start_game_index: int, seed_base: int, workers: int, slug: str) -> str:
    kernel_dir = os.path.join(KERNEL_ROOT, slug)
    if os.path.isdir(kernel_dir):
        for attempt in range(5):
            try:
                shutil.rmtree(kernel_dir)
                break
            except PermissionError:
                if attempt == 4:
                    raise
                time.sleep(2)
    os.makedirs(kernel_dir)

    shared_module_sources_b64 = {
        name: base64.b64encode(_read_source(os.path.join(SRC_DIR, f"{name}.py"))
                                .encode("utf-8")).decode("ascii")
        for name in SHARED_MODULE_ORDER
    }
    search_scorer_a_b64 = base64.b64encode(_read_source(code_a).encode("utf-8")).decode("ascii")
    search_scorer_b_b64 = base64.b64encode(_read_source(code_b).encode("utf-8")).decode("ascii")
    deck = _read_deck(DECK_PATH)

    driver_source = DRIVER_TEMPLATE % {
        "shared_module_sources_b64": shared_module_sources_b64,
        "shared_module_order": SHARED_MODULE_ORDER,
        "search_scorer_a_b64": search_scorer_a_b64,
        "search_scorer_b_b64": search_scorer_b_b64,
        "label_a": label_a, "label_b": label_b,
        "games": games,
        "start_game_index": start_game_index,
        "seed_base": seed_base,
        "workers": workers,
        "deck": deck,
    }
    with open(os.path.join(kernel_dir, "driver.py"), "w", encoding="utf-8") as f:
        f.write(driver_source)

    metadata = dict(KERNEL_METADATA_TEMPLATE)
    metadata["id"] = f"{get_kaggle_username()}/{slug}"
    metadata["title"] = slug.replace("-", " ")
    with open(os.path.join(kernel_dir, "kernel-metadata.json"), "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"Kernel package assembled at {kernel_dir} (id={metadata['id']}, "
          f"driver.py={len(driver_source)} bytes)")
    return kernel_dir


def push(kernel_dir: str) -> None:
    subprocess.run(kaggle_cmd("kernels", "push", "-p", kernel_dir), check=True)


def poll_and_fetch(slug: str, kernel_dir: str, poll_interval_s: float = 30.0,
                    timeout_s: float = 3600.0) -> dict | None:
    kernel_ref = f"{get_kaggle_username()}/{slug}"
    status_cmd = kaggle_cmd("kernels", "status", kernel_ref)
    start = time.time()
    while time.time() - start < timeout_s:
        result = subprocess.run(status_cmd, capture_output=True, text=True)
        print(result.stdout.strip())
        if "complete" in result.stdout.lower():
            break
        if "error" in result.stdout.lower() or "failed" in result.stdout.lower():
            print("Kernel run failed -- fetch output anyway for the error log/partial result.",
                  file=sys.stderr)
            break
        time.sleep(poll_interval_s)
    else:
        print(f"Timed out after {timeout_s}s waiting for kernel completion -- fetching "
              f"whatever partial output exists.", file=sys.stderr)

    output_cmd = kaggle_cmd("kernels", "output", kernel_ref, "-p", kernel_dir)
    subprocess.run(output_cmd, check=False)
    result_path = os.path.join(kernel_dir, "head_to_head_result.json")
    if os.path.exists(result_path):
        with open(result_path, encoding="utf-8") as f:
            return json.load(f)
    print(f"No head_to_head_result.json found in kernel output at {kernel_dir} -- check the "
          f"kernel's log.", file=sys.stderr)
    return None


def merge_results(parts: list[dict]) -> dict:
    a_wins = sum(p["a_wins"] for p in parts)
    b_wins = sum(p["b_wins"] for p in parts)
    draws = sum(p["draws"] for p in parts)
    crashes = sum(p["crashes"] for p in parts)
    n_decided = a_wins + b_wins + draws
    b_win_rate = (b_wins + 0.5 * draws) / n_decided if n_decided else 0.0
    se = math.sqrt(b_win_rate * (1 - b_win_rate) / n_decided) if n_decided else 0.0
    ci = (max(0.0, b_win_rate - 1.96 * se), min(1.0, b_win_rate + 1.96 * se))
    return {
        "label_a": parts[0]["label_a"], "label_b": parts[0]["label_b"],
        "games_requested": sum(p["games_requested"] for p in parts if not p.get("partial")
                                or p is parts[-1]),
        "games_completed": sum(p["games_completed"] for p in parts),
        "partial": False, "a_wins": a_wins, "b_wins": b_wins, "draws": draws,
        "crashes": crashes, "b_win_rate": b_win_rate, "b_win_rate_95ci": ci,
        "n_runs_merged": len(parts),
    }


def run_with_resume(code_a: str, label_a: str, code_b: str, label_b: str, games: int,
                     seed_base: int, workers: int, base_slug: str,
                     wait_timeout_s: float) -> dict | None:
    parts = []
    start_index = 0
    remaining = games
    attempt = 0
    max_attempts = 4
    while remaining > 0 and attempt < max_attempts:
        attempt += 1
        slug = base_slug if attempt == 1 else f"{base_slug}-resume{attempt}"
        kernel_dir = build(code_a, label_a, code_b, label_b, remaining, start_index, seed_base,
                            workers, slug)
        push(kernel_dir)
        result = poll_and_fetch(slug, kernel_dir, timeout_s=wait_timeout_s)
        if result is None:
            print(f"attempt {attempt}: no result at all -- stopping resume attempts.",
                  file=sys.stderr)
            break
        parts.append(result)
        completed = result["games_completed"]
        start_index += completed
        remaining -= completed
        if not result.get("partial") and completed >= result["games_requested"]:
            break
        if completed == 0:
            print(f"attempt {attempt}: 0 games completed -- stopping resume attempts to avoid "
                  f"a retry loop against a broken kernel.", file=sys.stderr)
            break
        print(f"attempt {attempt}: {completed} games completed, {remaining} remaining -- "
              f"launching a follow-up kernel." if remaining > 0 else
              f"attempt {attempt}: all {games} games completed.")

    if not parts:
        return None
    return merge_results(parts) if len(parts) > 1 else parts[0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--code-a", required=True, help="reference snapshot, e.g. frozen v1")
    ap.add_argument("--label-a", required=True)
    ap.add_argument("--code-b", required=True, help="candidate snapshot, e.g. v3 working tree")
    ap.add_argument("--label-b", required=True)
    ap.add_argument("--games", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--slug", default=None)
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--wait", action="store_true")
    ap.add_argument("--wait-timeout-s", type=float, default=3600.0)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    slug = args.slug or f"{args.label_b}-vs-{args.label_a}-head-to-head-2026-07-24"
    out_path = args.out or os.path.join(KERNEL_ROOT, f"{slug}_final_result.json")

    if not args.push:
        build(args.code_a, args.label_a, args.code_b, args.label_b, args.games, 0, args.seed,
              args.workers, slug)
        print("Package built but not pushed (pass --push). Review kernel-metadata.json's "
              "\"id\" field first.")
        return

    if not args.wait:
        kernel_dir = build(args.code_a, args.label_a, args.code_b, args.label_b, args.games, 0,
                            args.seed, args.workers, slug)
        push(kernel_dir)
        print("Pushed without --wait -- check status manually with "
              f"`kaggle kernels status {get_kaggle_username()}/{slug}`.")
        return

    result = run_with_resume(args.code_a, args.label_a, args.code_b, args.label_b, args.games,
                              args.seed, args.workers, slug, args.wait_timeout_s)
    if result is None:
        sys.exit("no usable result after all resume attempts.")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"\nFINAL: {json.dumps(result, indent=2)}")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
